version: "3"

services:
  springreact-front:
    container_name: springreact-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app

networks:
  default:
    driver: bridge
