version: "3"
services:
  springreact-front:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "/home/app/node_modules"
      - "./:/home/app"
